In [1]:
print(7)
# final_daily_sales

7

In [1]:
from sqlalchemy import create_engine

DB_USER = "muhammad-haroon"
DB_PASS = "haroon123"
DB_HOST = "localhost"      # or server IP
DB_PORT = "5432"
DB_NAME = "euro_parts_data"

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

In [2]:
engine

Engine(postgresql+psycopg2://muhammad-haroon:***@localhost:5432/euro_parts_data)

In [3]:
import pandas as pd
TABLE_NAME = "final_daily_sales"

query = f"SELECT * FROM {TABLE_NAME} limit 1000"

# ---- Read full table into DataFrame ----
df = pd.read_sql_query(query, engine)

# ---- Save to CSV ----
df.to_csv(f"{TABLE_NAME}.csv", index=False)

print("✅ Export completed successfully")

✅ Export completed successfully

In [5]:
TABLE_NAME = "product_template"

query = f"SELECT * FROM {TABLE_NAME} limit 1000"

# ---- Read full table into DataFrame ----
df = pd.read_sql_query(query, engine)

# ---- Save to CSV ----
#df.to_csv(f"{TABLE_NAME}.csv", index=False)
df.head()
#print("✅ Export completed successfully")

,id,message_main_attachment_id,sequence,categ_id,uom_id,uom_po_id,company_id,color,create_uid,write_uid,...,rating_last_value,base_unit_count,out_of_stock_message,allow_out_of_stock_order,show_availability,available_threshold,qty_sold,views,top_selling,most_viewed
0,189500,NaN,1,9,32,32,1,None,2,1,...,0.0,1.0,None,False,None,5.0,None,None,None,None
1,189501,NaN,1,9,32,32,1,None,2,1,...,0.0,1.0,None,False,None,5.0,None,None,None,None
2,189502,NaN,1,12,32,32,1,None,2,1,...,0.0,1.0,None,False,None,5.0,None,None,None,None
3,189503,NaN,1,9,32,32,1,None,2,1,...,0.0,1.0,None,False,None,5.0,None,None,None,None
4,189504,NaN,1,9,32,32,1,None,2,1,...,0.0,1.0,None,False,None,5.0,None,None,None,None

In [6]:
table=df

In [7]:
df.head()

,id,message_main_attachment_id,sequence,categ_id,uom_id,uom_po_id,company_id,color,create_uid,write_uid,...,rating_last_value,base_unit_count,out_of_stock_message,allow_out_of_stock_order,show_availability,available_threshold,qty_sold,views,top_selling,most_viewed
0,189500,NaN,1,9,32,32,1,None,2,1,...,0.0,1.0,None,False,None,5.0,None,None,None,None
1,189501,NaN,1,9,32,32,1,None,2,1,...,0.0,1.0,None,False,None,5.0,None,None,None,None
2,189502,NaN,1,12,32,32,1,None,2,1,...,0.0,1.0,None,False,None,5.0,None,None,None,None
3,189503,NaN,1,9,32,32,1,None,2,1,...,0.0,1.0,None,False,None,5.0,None,None,None,None
4,189504,NaN,1,9,32,32,1,None,2,1,...,0.0,1.0,None,False,None,5.0,None,None,None,None